CREATE TABLE asociado (
    --id_asociado INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_asociado INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR2(20) NOT NULL,
    apellido    VARCHAR2(20) NOT NULL
);

CREATE TABLE contacto (
    id_contacto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR2(25) NOT NULL
);

CREATE TABLE hospital (
    id_hospital INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR2(35) NOT NULL,
    direccion   VARCHAR2(50) NOT NULL
);

CREATE TABLE lugar (
    id_lugar INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre   VARCHAR2(50)
);

CREATE TABLE tratamiento (
    id_tratamiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         VARCHAR2(50) NOT NULL,
    efectividad    INTEGER NOT NULL
);
CREATE TABLE estado(
    id_estado INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR2(20) NOT NULL
);

CREATE TABLE victima (
    id_victima           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre               VARCHAR2(25) NOT NULL,
    apellido             VARCHAR2(30) NOT NULL,
    direccion            VARCHAR2(70) NOT NULL,
    fecha_muerte         TIMESTAMP,
    fecha_confirmacion   TIMESTAMP NOT NULL,
    fecha_sospecha       TIMESTAMP NOT NULL,
    id_hospital 				 INTEGER,
    id_estado            INTEGER,
		CONSTRAINT victima_hospital_fk FOREIGN KEY ( id_hospital ) REFERENCES hospital(id_hospital),
		CONSTRAINT victima_estado_fk FOREIGN KEY ( id_estado ) REFERENCES estado(id_estado)
);

CREATE TABLE ubicacion (
		id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_llegada      TIMESTAMP NOT NULL,
    fecha_salida       TIMESTAMP NOT NULL,
		id_lugar 					 INTEGER NOT NULL,
		id_victima 				 INTEGER NOT NULL,
		CONSTRAINT ubicacion_lugar_fk FOREIGN KEY ( id_lugar ) REFERENCES lugar(id_lugar),
		CONSTRAINT ubicacion_victima_fk FOREIGN KEY ( id_victima ) REFERENCES victima(id_victima)
);

CREATE TABLE observacion (
		id                         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_inicio               TIMESTAMP NOT NULL,
    fecha_fin                  TIMESTAMP NOT NULL,
    efectividad                INTEGER NOT NULL,
		id_tratamiento   					 INTEGER NOT NULL,
		id_victima								 INTEGER NOT NULL, 
		CONSTRAINT observacion_tratamiento_fk FOREIGN KEY ( id_tratamiento ) REFERENCES tratamiento(id_tratamiento),
		CONSTRAINT observacion_victima_fk FOREIGN KEY ( id_victima ) REFERENCES victima(id_victima)
);

CREATE TABLE relacion (
    id_relacion          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_conocio        TIMESTAMP NOT NULL,
		id_victima 					 INTEGER NOT NULL,
		id_asociado					 INTEGER NOT NULL, 
		CONSTRAINT relacion_victima_fk FOREIGN KEY ( id_victima ) REFERENCES victima(id_victima),
		CONSTRAINT relacion_asociado_fk FOREIGN KEY ( id_asociado ) REFERENCES asociado(id_asociado)
);

CREATE TABLE interaccion (
		id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_inicio         TIMESTAMP NOT NULL,
    fecha_fin            TIMESTAMP NOT NULL,
		id_contacto 				 INTEGER NOT NULL, 
		id_relacion					 INTEGER NOT NULL, 
		CONSTRAINT interaccion_contacto_fk FOREIGN KEY ( id_contacto ) REFERENCES contacto(id_contacto),
		CONSTRAINT interaccion_relacion_fk FOREIGN KEY ( id_relacion ) REFERENCES relacion(id_relacion)
)$
--           Insert data in model
--Asociado
INSERT INTO asociado (nombre,apellido) SELECT distinct NOMBRE_ASOCIADO,APELLIDO_ASOCIADO  FROM temporal WHERE nombre_asociado IS NOT null;
--Contacto
INSERT INTO contacto (nombre) SELECT distinct contacto_fisico  FROM temporal WHERE contacto_fisico IS NOT null;
--Hospital
INSERT INTO hospital (nombre,direccion) SELECT distinct nombre_hospital,direccion_hospital  FROM temporal WHERE nombre_hospital IS NOT null;
--Lugar
INSERT INTO lugar (nombre) SELECT distinct ubicacion_victima  FROM temporal WHERE ubicacion_victima IS NOT null;
--Tratamiento
INSERT INTO tratamiento  (nombre,efectividad) SELECT distinct tratamiento,efectividad  FROM TEMPORAL WHERE tratamiento IS NOT null;
--Estado
INSERT INTO estado  (nombre) SELECT distinct estado_victima  FROM TEMPORAL WHERE estado_victima IS NOT null;
--Victima
INSERT INTO VICTIMA (nombre,apellido,direccion,fecha_muerte,id_estado,fecha_confirmacion,fecha_sospecha,id_hospital)
SELECT DISTINCT NOMBRE_victima, apellido_victima,direccion_victima,fecha_muerte,id_estado,fecha_confirmacion,primera_sospecha ,id_hospital 
FROM TEMPORAL 
left JOIN HOSPITAL ON NOMBRE_HOSPITAL=nombre AND DIRECCION_HOSPITAL=direccion
JOIN estado ON estado.nombre=estado_victima
WHERE nombre_victima IS NOT NULL;
--Ubicacion
INSERT INTO UBICACION (fecha_llegada,fecha_salida,id_lugar,id_victima)
SELECT DISTINCT fecha_llegada,fecha_retiro,id_lugar,id_victima FROM TEMPORAL 
JOIN LUGAR  ON ubicacion_victima=lugar.nombre 
JOIN victima ON victima.nombre=nombre_victima AND victima.apellido=apellido_victima
WHERE nombre_victima IS NOT null;
--Observacion
INSERT INTO OBSERVACION  (fecha_inicio,fecha_fin,efectividad,id_tratamiento,id_victima)
SELECT DISTINCT inicio_tratamiento,fin_tratamiento,efectividad_victima,TRATAMIENTO.id_tratamiento,victima.id_victima FROM TEMPORAL 
INNER JOIN TRATAMIENTO ON temporal.TRATAMIENTO=TRATAMIENTO.nombre
INNER JOIN victima ON temporal.NOMBRE_VICTIMA=victima.nombre AND APELLIDO_VICTIMA=victima.apellido
WHERE INICIO_TRATAMIENTO  IS NOT null;
--Relacion
INSERT INTO RELACION  (fecha_conocio,id_victima,id_asociado)
SELECT DISTINCT FECHA_CONOCIO,id_victima,id_asociado FROM TEMPORAL 
INNER JOIN victima ON NOMBRE_VICTIMA=victima.nombre AND APELLIDO_VICTIMA=victima.apellido
INNER JOIN ASOCIADO ON NOMBRE_ASOCIADO=asociado.nombre AND APELLIDO_ASOCIADO=asociado.apellido
WHERE FECHA_CONOCIO  IS NOT null;
--Interaccion
INSERT INTO INTERACCION  (fecha_inicio,fecha_fin,id_contacto,id_relacion)
SELECT DISTINCT t.INICIO_CONTACTO,t.FIN_CONTACTO ,id_contacto,r.ID_RELACION  FROM TEMPORAL t
INNER JOIN CONTACTO c ON t.CONTACTO_FISICO=c.nombre
INNER JOIN VICTIMA v ON t.NOMBRE_VICTIMA=v.NOMBRE AND t.APELLIDO_VICTIMA=v.APELLIDO 
INNER JOIN ASOCIADO a ON t.NOMBRE_ASOCIADO=a.NOMBRE AND t.APELLIDO_ASOCIADO=a.APELLIDO 
INNER JOIN RELACION r ON r.ID_VICTIMA=v.ID_VICTIMA AND r.ID_ASOCIADO=a.ID_ASOCIADO 
WHERE INICIO_CONTACTO IS NOT NULL;
