CREATE TABLE temporal (
	nombre_victima VARCHAR(20),
	apellido_victima VARCHAR(20),
	direccion_victima VARCHAR(50),
	primera_sospecha TIMESTAMP,
	fecha_confirmacion TIMESTAMP,
	fecha_muerte TIMESTAMP,
	estado_victima VARCHAR(20),
	nombre_asociado VARCHAR(20),
	apellido_asociado VARCHAR(20),
	fecha_conocio TIMESTAMP,
	contacto_fisico VARCHAR(20),
	inicio_contacto TIMESTAMP,
	fin_contacto TIMESTAMP,
	nombre_hospital VARCHAR(50),
	direccion_hospital VARCHAR(50),
	ubicacion_victima VARCHAR (50),
	fecha_llegada TIMESTAMP,
	fecha_retiro TIMESTAMP,
	tratamiento VARCHAR(50),
	efectividad INT,
	inicio_tratamiento TIMESTAMP,
	fin_tratamiento TIMESTAMP,
	efectividad_victima INT
)
