DROP TABLE interaccion;
DROP TABLE relacion;
DROP TABLE observacion;
DROP TABLE ubicacion;
DROP TABLE victima;
DROP TABLE tratamiento;
DROP TABLE lugar;
DROP TABLE hospital;
DROP TABLE contacto;
DROP TABLE asociado
